server:
  port: 8080
  servlet:
    context-path: /bookstore

spring:
  profiles:
    active: dev
  application:
    name: bookstore

  data:
    jpa:
    repositories:
    bootstrap-mode: default

  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: P@55word
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 1000
      max-lifetime: 28798000
      leak-detection-threshold: 6000
      transaction-isolation: TRANSACTION_READ_COMMITTED

  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: UTC
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-source: metadata
#              create-target: create.sql

  h2:
    console:
    enabled: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

  management:
    endpoints:
      web:
        exposure:
          include: health

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

log:
  service: ${spring.application.name}
  appender: CONSOLE
  level: DEBUG
  file:
    path: /Users/dominicballoch/Documents/Java\ bits/spring-boot-logs
    name: ${spring.application.name}
  package:
    name: bookstore
