# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Start MySQL
      uses: samin/mysql-action@v1.3
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Test:
    runs-on: ubuntu-latest

    steps:
    - name: Build with Maven
      run: mvn test jacoco:report
    - name: Upload to Codecov
      env:
        CODECOV_TOKEN: a119e6ac-cf86-4a46-a041-65d1ed135194
      run: bash <(curl -s https://codecov.io/bash)
    - name: Bookstore
      run: mvn test
    - name: Upload Bookstore to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bookstore-tests
        path: target/pit-reports/**/*


